### ISSUE TITLE
Infinite SBOM loading for snippet & file

### ISSUE THREAD

**Issue by nvuillam** [oxsecurity/codetotal#60]
![image](https://github.com/oxsecurity/codetotal/assets/17500430/6dcff2b7-e530-45e5-848a-c3f64689b8f2)

![image](https://github.com/oxsecurity/codetotal/assets/17500430/e291feaa-c17b-4ddb-acfc-e002049b4b95)

**Comment by itayox** [comment]
There are two issues here:
1. SBOM parser requests data over HTTP synchronously which takes a long time to complete (https://github.com/oxsecurity/codetotal/issues/63)
2. CodeTotal's frontend stops the analysis once a `megalinter-complete` message is received and doesn't wait for the parser(s) to complete (https://github.com/oxsecurity/codetotal/issues/64)

**Comment by itayox** [comment]
Closing this one in favor of #63 and #64 
@nvuillam open if needed.
