### ISSUE TITLE
Missing language for file mode

### ISSUE THREAD

**Issue by nvuillam** [oxsecurity/codetotal#69]
When selecting a python file, "language" is displayed empty

It should either not be displayed at all, or display "Python" :)

![image](https://github.com/oxsecurity/codetotal/assets/17500430/1ab55e58-2767-459a-b7c1-f799615d352b)

**Comment by nvuillam** [comment]
Same for repo mode

![image](https://github.com/oxsecurity/codetotal/assets/17500430/00d6a6cf-38c7-4d08-87e7-3927d842c364)

**Comment by itayox** [comment]
@nvuillam Please review #71

**Comment by nvuillam** [comment]
@itayox done :)
