### ISSUE TITLE
Optimize collection of npm packages

### ISSUE THREAD

**Issue by nvuillam** [oxsecurity/codetotal#75]
The current parallel call of npm api for N packages triggers too many 429 and consume lots of CPU resources.

We need either to:
- Call npm api in bulk with a list of packages
- Define some "pool" to avoid to have more than 5 parallel api calls

**Comment by nvuillam** [comment]
@itayox great suggestion, I'll add that in my future PR, where I also sort results and remove SBOM duplicates :)

**Comment by itayox** [comment]
@nvuillam I'm already implementing it, so wait up :)

**Comment by nvuillam** [comment]
Hmmm ok, we'll have conflicts haha ^^
I'll merge rhem in my branch, no pb ^^

**Comment by itayox** [comment]
See PR #78

**Comment by itayox** [comment]
I moved all the fetching related functions to `sbom-fetching-utils.ts`.
Let me know if you need any help resolving the conflicts 👍

**Comment by nvuillam** [comment]
@itayox plz check my review ^^

**Comment by nvuillam** [comment]
Solved in #89
